package com.techjava.springbootapachecxfservice.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-12-04T16:33:30.035+01:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "BookingServiceService", 
                  wsdlLocation = "classpath:wsdl/BookingService.wsdl",
                  targetNamespace = "http://service.springbootapachecxfservice.techjava.com/") 
public class BookingServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.springbootapachecxfservice.techjava.com/", "BookingServiceService");
    public final static QName BookingServicePort = new QName("http://service.springbootapachecxfservice.techjava.com/", "BookingServicePort");
    static {
        URL url = BookingServiceService.class.getClassLoader().getResource("wsdl/BookingService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(BookingServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/BookingService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public BookingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BookingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BookingServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BookingServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BookingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "BookingServicePort")
    public BookingService getBookingServicePort() {
        return super.getPort(BookingServicePort, BookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingService
     */
    @WebEndpoint(name = "BookingServicePort")
    public BookingService getBookingServicePort(WebServiceFeature... features) {
        return super.getPort(BookingServicePort, BookingService.class, features);
    }

}
